server:
  port: 8081

spring:
  datasource:
    # 驱动配置信息
    #url: jdbc:mysql://127.0.0.1:3306/demospringboot
    url: jdbc:mysql://localhost:3306/demospringboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

  # Redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    ## 连接池中的最大连接数
    poolMaxTotal: 10
    ## 连接池中的最大空闲连接
    poolMaxIdle: 10
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
    poolMaxWait: 3
    # 链接超时时间（毫秒）
    timeout: 1000

mybatis:
  type-aliases-package: com.spring.springboot.entity
  mapper-locations: classpath:mapper/*.xml


logging:
  #日志输出级别
  level:
    org.spring.springboot: debug
  #配置日志文件路径
  config: classpath:logback-spring-dev.xml
  # 不指定路径在当前项目下生成springboot.log日志
  # 可以指定完整的路径；
  #file: D:/SpringBootTest/springboot.log
  # 在当前磁盘的根路径下创建spring文件夹和里面的log文件夹,使用 spring.log 作为默认文件
  #path: /spring/log
  # 在控制台输出的日志的格式
  #pattern:
  #  console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
  # 指定文件中日志输出的格式
  #  file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
  home: 'D:/dev'

### xxl-job 管理平台
xxl:
  job:
    admin:
      #调度中心部署跟地址：如调度中心集群部署存在多个地址则用逗号分隔。
      #执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"。
      addresses: http://localhost:8080/xxl-job-admin

    ### xxl-job, access token
    accessToken:

    ### xxl-job executor address 任务执行器名称
    #分别配置执行器的名称、ip地址、端口号
    #注意：如果配置多个执行器时，防止端口冲突
    executor:
      appname: executorDemo
      ip:
      port: 9999
      ### xxl-job log path
      #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logpath: /data/applogs/pbase-job/jobhandler
      ### xxl-job log retention days
      #执行器Log文件定期清理功能，指定日志保存天数，日志文件过期自动删除。限制至少保持3天，否则功能不生效；
      #-1表示永不删除
      logretentiondays: 30
